"""Mock patient roster for Follow-up Today and map rendering."""

from __future__ import annotations

PATIENTS = [
    {
        "id": "p001",
        "pseudonym": "Amina K.",
        "age_months": 24,
        "avatar": "🧒",
        "lat": -1.9542,
        "lon": 30.0639,
        "last_visit_date": "2026-02-12",
        "last_visit_summary": "Fever+cough, RR 58, danger sign present. Follow-up requested in 48 hours.",
        "last_visit_fields": {
            "rr": 58,
            "danger_sign": True,
            "unable_to_drink": True,
            "vomiting_everything": True,
            "chest_indrawing": True,
        },
        "current_visit_seed": {
            "rr": 52,
            "danger_sign": True,
            "unable_to_drink": True,
            "vomiting_everything": True,
            "chest_indrawing": True,
        },
        "follow_up_due": True,
        "status": "urgent follow-up",
    },
    {
        "id": "p002",
        "pseudonym": "Jonas M.",
        "age_months": 30,
        "avatar": "👦",
        "lat": -1.9518,
        "lon": 30.0671,
        "last_visit_date": "2026-02-13",
        "last_visit_summary": "Persistent cough, low intake. Family advised immediate reassessment.",
        "last_visit_fields": {
            "rr": 60,
            "danger_sign": True,
            "unable_to_drink": True,
            "vomiting_everything": False,
            "chest_indrawing": True,
        },
        "current_visit_seed": {
            "rr": 56,
            "danger_sign": True,
            "unable_to_drink": True,
            "vomiting_everything": False,
            "chest_indrawing": True,
        },
        "follow_up_due": True,
        "status": "urgent follow-up",
    },
    {
        "id": "p003",
        "pseudonym": "Lina T.",
        "age_months": 18,
        "avatar": "👧",
        "lat": -1.9577,
        "lon": 30.0616,
        "last_visit_date": "2026-02-10",
        "last_visit_summary": "Mild fever; active; no danger signs. Routine revisit.",
        "last_visit_fields": {
            "rr": 38,
            "danger_sign": False,
            "unable_to_drink": False,
            "vomiting_everything": False,
            "chest_indrawing": False,
        },
        "current_visit_seed": {
            "rr": 40,
            "danger_sign": False,
            "unable_to_drink": False,
            "vomiting_everything": False,
            "chest_indrawing": False,
        },
        "follow_up_due": True,
        "status": "normal follow-up",
    },
    {
        "id": "p004",
        "pseudonym": "Biko R.",
        "age_months": 40,
        "avatar": "🧑",
        "lat": -1.9594,
        "lon": 30.0692,
        "last_visit_date": "2026-02-11",
        "last_visit_summary": "Cough improving; eating better; no danger signs.",
        "last_visit_fields": {
            "rr": 36,
            "danger_sign": False,
            "unable_to_drink": False,
            "vomiting_everything": False,
            "chest_indrawing": False,
        },
        "current_visit_seed": {
            "rr": 34,
            "danger_sign": False,
            "unable_to_drink": False,
            "vomiting_everything": False,
            "chest_indrawing": False,
        },
        "follow_up_due": True,
        "status": "normal follow-up",
    },
    {
        "id": "p005",
        "pseudonym": "Mara J.",
        "age_months": 20,
        "avatar": "👶",
        "lat": -1.9555,
        "lon": 30.0587,
        "last_visit_date": None,
        "last_visit_summary": "No prior visit.",
        "last_visit_fields": {},
        "current_visit_seed": {},
        "follow_up_due": False,
        "status": "new visit",
    },
    {
        "id": "p006",
        "pseudonym": "Nuru P.",
        "age_months": 15,
        "avatar": "👶",
        "lat": -1.9521,
        "lon": 30.0601,
        "last_visit_date": None,
        "last_visit_summary": "No prior visit.",
        "last_visit_fields": {},
        "current_visit_seed": {},
        "follow_up_due": False,
        "status": "new visit",
    },
]


def get_patient_by_id(patient_id: str) -> dict | None:
    for patient in PATIENTS:
        if patient["id"] == patient_id:
            return patient
    return None
